### ISSUE TITLE
Adding other users/groups

### ISSUE THREAD

**Issue by krispykiq** [zaini/nyaascraper#4]
I'm trying to add other groups/users to scrape from nyaa. Unfortunately I'm having a problem where it says the episodes could not be loaded. 

It fails at the part of:

`rows = soup.find_all('tr', class_='success')`

I added this:

`ssa_url = URL('https://nyaa.si/user/SmallSizedAnimations?f=0&c=0_0&q={}&o=desc&p={}', -2, -1)`

and instead of rows valuing a lot of stuff it only values to [] 

I also added this but it has the same results:

`ember_url = URL('https://nyaa.si/user/Ember_Encodes?f=0&c=0_0&q={}&o=desc&p={}', -3, -2)`

**Comment by zaini** [comment]
This is occurring because I'm using class_='success', which works for the groups I have but doesn't work for those groups because for them, class_='danger'

I've made the fixes here: https://github.com/zaini/nyaascraper/pull/5 and added the groups you've sent me, although they don't all follow the format that's required so some stuff might not download properly but it's there none the less and you can tweak it further if you want.
